"""
Copy model artifacts generated by stock_trading_bot.py into trading-app-backend/models.

Usage:
  python copy_models.py
"""

from __future__ import annotations

from pathlib import Path
import shutil


ROOT = Path(__file__).resolve().parent.parent
BACKEND = Path(__file__).resolve().parent
MODELS_DIR = BACKEND / "models"

FILES = [
    "nifty_xgb_model.pkl",
    "nifty_lgb_model.pkl",
    "nifty_cat_model.pkl",
    "nifty_tcn_model.keras",
    "nifty_scaler.pkl",
    "nifty_features.pkl",
]


def main() -> None:
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    copied = []
    missing = []

    for filename in FILES:
        src = ROOT / filename
        dst = MODELS_DIR / filename
        if src.exists():
            shutil.copy2(src, dst)
            copied.append(filename)
        else:
            missing.append(filename)

    print(f"Copied {len(copied)} file(s) to {MODELS_DIR}:")
    for name in copied:
        print(f"  - {name}")

    if missing:
        print("\nMissing in project root:")
        for name in missing:
            print(f"  - {name}")


if __name__ == "__main__":
    main()
