"""
engine/signals.py — Load trained models and generate live BUY/SELL signals.

IMPORTANT: Copy your trained model files into the models/ folder:
  models/xgb_model.pkl
  models/lgb_model.pkl
  models/cat_model.pkl
  models/scaler.pkl
  models/feature_cols.pkl
  models/tcn_model.pkl  (optional — only if TF was used)

These are generated by running:
  python stock_trading_bot.py train
on your local machine.
"""

from __future__ import annotations
import os
import sys
import joblib
import numpy as np
import pandas as pd
from typing import Optional
from engine.config import (
    LOOKBACK, MIN_CONFIDENCE, MIN_CONFIDENCE_SHORT,
    NEWS_BLOCK_THRESHOLD, XGB_MODEL_FILE, LGB_MODEL_FILE,
    CAT_MODEL_FILE, TCN_MODEL_FILE, SCALER_FILE, FEATURE_COLS_FILE,
)

# ── Module-level model cache ─────────────────────────────────────────────────
_models_cache: dict | None = None


def load_models() -> dict:
    """Load all trained models from disk (cached after first load)."""
    global _models_cache
    if _models_cache is not None:
        return _models_cache

    if not os.path.exists(SCALER_FILE):
        raise FileNotFoundError(
            f"No trained models found in models/. "
            "Copy your model files there and restart the server."
        )

    xgb_m   = joblib.load(XGB_MODEL_FILE) if os.path.exists(XGB_MODEL_FILE) else None
    lgb_m   = joblib.load(LGB_MODEL_FILE) if os.path.exists(LGB_MODEL_FILE) else None
    cat_m   = joblib.load(CAT_MODEL_FILE) if os.path.exists(CAT_MODEL_FILE) else None
    scaler  = joblib.load(SCALER_FILE)
    feature_cols = joblib.load(FEATURE_COLS_FILE)

    tcn_m = None
    if os.path.exists(TCN_MODEL_FILE):
        try:
            import tensorflow as tf
            tcn_m = tf.keras.models.load_model(TCN_MODEL_FILE)
        except Exception:
            pass

    _models_cache = {
        "xgb": xgb_m, "lgb": lgb_m, "cat": cat_m,
        "tcn": tcn_m, "scaler": scaler, "feature_cols": feature_cols,
    }
    print("[Models] All models loaded and cached.")
    return _models_cache


def models_ready() -> bool:
    """Return True if models have been loaded successfully."""
    try:
        load_models()
        return True
    except FileNotFoundError:
        return False


def _ensemble_predict(X: np.ndarray, models: dict) -> np.ndarray:
    """
    Run the 4-model weighted ensemble and return probability of BUY.
    Weights: XGB 28% | LGB 22% | CAT 28% | TCN 22%
    """
    probs = []

    if models["xgb"] is not None:
        p = models["xgb"].predict_proba(X)[:, 1]
        probs.append((p, 0.28))

    if models["lgb"] is not None:
        p = models["lgb"].predict_proba(X)[:, 1]
        probs.append((p, 0.22))

    if models["cat"] is not None:
        p = models["cat"].predict_proba(X)[:, 1]
        probs.append((p, 0.28))

    if models["tcn"] is not None:
        try:
            seq = X.reshape(X.shape[0], LOOKBACK, -1)
            p = models["tcn"].predict(seq, verbose=0).flatten()
            probs.append((p, 0.22))
        except Exception:
            pass

    if not probs:
        raise RuntimeError("No models available for prediction")

    # Normalise weights
    total_w = sum(w for _, w in probs)
    ensemble = sum(p * (w / total_w) for p, w in probs)
    return ensemble


def generate_signals(df_5m: pd.DataFrame, tickers: list[str]) -> pd.DataFrame:
    """
    Generate BUY/SELL signals for the given tickers.
    Returns a DataFrame with columns:
      ticker, signal, confidence, close, news_score, combined
    sorted by combined score descending.
    """
    models = load_models()
    scaler      = models["scaler"]
    feature_cols = models["feature_cols"]

    rows = []
    for ticker in tickers:
        tick_df = df_5m[df_5m["ticker"] == ticker].sort_index().tail(LOOKBACK + 5)
        if len(tick_df) < LOOKBACK:
            continue

        # Select features available in this snapshot
        avail = [f for f in feature_cols if f in tick_df.columns]
        if len(avail) < len(feature_cols) * 0.5:
            continue

        snap = tick_df[avail].iloc[-1:].copy()
        snap = snap.fillna(0)

        try:
            X = scaler.transform(snap[avail])
            prob = float(_ensemble_predict(X, models)[0])
        except Exception:
            continue

        if prob >= MIN_CONFIDENCE / 100:
            signal = "BUY"
            conf   = prob * 100
        elif (1 - prob) >= MIN_CONFIDENCE_SHORT / 100:
            signal = "SELL"
            conf   = (1 - prob) * 100
        else:
            continue

        rows.append({
            "ticker":     ticker,
            "signal":     signal,
            "confidence": round(conf, 2),
            "close":      float(tick_df["close"].iloc[-1]),
            "news_score": 0.0,   # News sentiment added later if needed
            "combined":   round(prob * 0.7, 4),
        })

    if not rows:
        return pd.DataFrame()

    picks = pd.DataFrame(rows).sort_values("combined", ascending=False)

    # Block BUY signals with very negative news
    picks = picks[
        ~((picks["signal"] == "BUY") & (picks["news_score"] < NEWS_BLOCK_THRESHOLD))
    ].reset_index(drop=True)

    return picks
